### ISSUE TITLE
Allow developers to incorporate default transitions into their own transitions

### ISSUE THREAD

**Issue by jakearchibald** [WICG/view-transitions#117]
**Use-case: An element appears on the incoming page only, but the developer wants it to appear to slide from being another transition element**

Imagine Page-A is a grid of thumbnails, and Page-B contains the full image and description.

A nice transition would be for thumbnail to grow into the full image, while the description slides out from underneath.

For the thumbnail-to-image transition, a bit of JS would be required to tag the appropriate thumbnail, but from there on, the default transition will do a good job.

Things get trickier with the description, as it doesn't have an equivalent on Page-A, so the default will be for it to fade-in in its final place.

One option would be to create a dummy description element in Page-A, and position it behind the thumbnail.

One of the reasons we're creating shared-element-transitions is because messing around with the DOM like this is tricky and full of booby-traps. E.g., if the page comes back from bfcache, will the developer remember to remove this dummy element?

---

<details>
<summary>Proposal involving a sort-of custom vars approach, but I'm not sure this solves all the cases</summary>
I wonder it would be useful in both cases to be able to reference the default start & end styles of another element. As in, a CSS function like `transition-container-outgoing(tag, style-prop)` which returns the outgoing value of `style-prop` for the transition element with tag `tag`.

You could say that the generated style for a container named foo is:

```css
@keyframes foo-container-keyframes {
  from {
    transform: transition-container-outgoing(foo, transform);
    width: transition-container-outgoing(foo, width);
    height: transition-container-outgoing(foo, height);
    opacity: transition-container-outgoing(foo, opacity);
  }
  to {
    transform: transition-container-incoming(foo, transform);
    width: transition-container-incoming(foo, width);
    height: transition-container-incoming(foo, height);
    opacity: transition-container-incoming(foo, opacity);
  }
}

::page-transition-container(foo) {
  animation: 1s linear both foo-container-keyframes;
}
```

Or, if we had another function which returned the tag name for that particular element, we could massively cut down on the number of dynamic styles that we need, and maybe eliminate them altogether:

```css
@keyframes container-keyframes {
  from {
    transform: transition-container-outgoing(transition-tag(), transform);
    width: transition-container-outgoing(transition-tag(), width);
    height: transition-container-outgoing(transition-tag(), height);
    opacity: transition-container-outgoing(transition-tag(), opacity);
  }
  to {
    transform: transition-container-incoming(transition-tag(), transform);
    width: transition-container-incoming(transition-tag(), width);
    height: transition-container-incoming(transition-tag(), height);
    opacity: transition-container-incoming(transition-tag(), opacity);
  }
}

::page-transition-container(*) {
  animation: 1s linear both container-keyframes;
}
```

The above could be static styles, as they don't change per transition.

`transition-tag()` could be replaced with CSS custom properties, but I'm not sure if the browser should be generating those itself.

For the use-case:

```css
@keyframes description-keyframes {
  from {
    transform:
      /* Step 3, slide it behind the thumbnail */
      translateY(-100%)
      /* Step 2, move it below the thumbnail */
      translateY(transition-container-outgoing(thumbnail, height))
      /* Step 1, put the description in the position of the thumbnail */
      transition-container-outgoing(thumbnail, transform);

    width: transition-container-outgoing(thumbnail, width);
    height: auto;
    opacity: 0;
  }
  to {
    transform: transition-container-incoming(transition-tag(), transform);
    width: transition-container-incoming(transition-tag(), width);
    height: transition-container-incoming(transition-tag(), height);
    opacity: 1;
  }
}

::page-transition-container(description) {
  animation: 1s linear both description-keyframes;
}
```

Using only CSS, the developer would be able to position the description according to the position of the thumbnail from the previous page.
</details>

**Comment by stuartlangridge** [comment]
Clarifying a little, the thing I wanted to do in the above-linked demonstration is not particularly to create an animation along the transition path: that's an example only of the sort of thing that might be possible. In essence, the issue is that if I use the shared-element-transition API to appear to animate a thing from one place to another, and I use `page-transition-tag: mytag` to do that, then the transition I get for free is one in which size and position are animated for me. This is great: it's essentially as if the s-e-t API automatically creates CSS which would look something like:
```css
::page-transition-outgoing-image(my-tag) { animation-name: kf; }
@keyframes kf {
  to: { transform: translate(X, Y) scale(S); }
}
```
where those X and Y and S figures are _calculated for me_. I don't have to work them out; the s-e-t API takes care of it, and this is a big part of why using this API in an SPA environment is a big timesaver.

If I want to alter how that `transform` happens, though -- maybe I want to make it happen in multiple steps, or for the scale to go very small and then to the destination scale, or to animate along a path with offset-path, or any other alteration from the invisibly created keyframe setup that the s-e-t API does for me, then I have to add my own `@keyframes` item instead, replacing the invisibly created one. And... I don't know what X and Y and S should be. If I have to calculate them myself... well, if I wanted to do that, and write a load of JavaScript _to_ do it, then I'd already be doing this transition animation with FLIP, probably. In that situation the new s-e-t API loses quite a lot of its compelling nature. (Not all of it; there are still many benefits and edge cases that this API provides, and MPA stuff is impossible without it.)

I don't think there's an obvious solution here. The idea that shared-element-transitions is entirely powered by CSS and I don't need to write lots of JS and do lots of calculations myself is very compelling, and I think that should be preserved. However, I'd also like a way where I can alter the transition that it decides for me without having to wholly replace that translation with one I have to calculate and build myself from scratch.
