### ISSUE TITLE
Wildcard transition names in selectors

### ISSUE THREAD

**Issue by matthewp** [WICG/view-transitions#213]
[This blog post](https://daverupert.com/2023/05/getting-started-view-transitions/) explains how you might add separate view-transition-names when operating on a list. Like so:

```nunjunks
<div class="posts">
{% foreach post in posts %}
  <a style="view-transition-name: post-{{ post.id }}" href="{{ post.url }}">{{ post.title }}</a>
{% endforeach %}
</div>
```

Notice here that this creates a dynamic `view-transition-name` per anchor. I don't think there is a way to then style these transitions old/new views. You can't currently do:

```css
::view-transition-old(post-*) {
  animation: fade 0.2s linear forwards;
}
```

Maybe there's another/better way to do this?
