### ISSUE TITLE
Allow configuration of paired transitions to clip instead of scale when animating size

### ISSUE THREAD

**Issue by jakearchibald** [WICG/view-transitions#33]
I've been thinking about how to transition something like:

```css
h1 {
  background: #eee;
  border-bottom: 10px solid #ccc;
  padding: 1rem;
}
```

Where it goes to/from:

<img width="576" alt="Screenshot 2021-06-21 at 10 23 49" src="https://user-images.githubusercontent.com/93594/122739426-e123e080-d27a-11eb-9acd-74b80571f79c.png">

<img width="572" alt="Screenshot 2021-06-21 at 10 24 14" src="https://user-images.githubusercontent.com/93594/122739439-e4b76780-d27a-11eb-98f4-d04b0e89b830.png">

I guess you'd need to split it up into three elements:

```html
<h1>
  <span class="heading-content">Heading content</span>
  <span class="heading-border"></span>
</h1>
```

```css
.heading-border {
  display: block;
  height: 10px;
  background: #ccc;
}
.heading-content {
  display: block;
  padding: 1rem;
  background: #eee;
}
```

…where the border does a shared element transition like we have now, but the content would only transition via a cross-fade and clipping change.

Does that make sense?

I guess it just emphasises that we need clipping-based transitions.
