### ISSUE TITLE
Interactivity during transitions

### ISSUE THREAD

**Issue by jakearchibald** [WICG/view-transitions#50]
https://svelte.dev/examples#animate - would SET cover a use-case like this? It seems to depend on two things:

- Click events working during the transition
- The transitions composing together, as it's possible for one to start while another is in progress

**Comment by khushalsagar** [comment]
Could you clarify a bit more about the use-case. It seems like the click initiates the transition and then no input is needed while the transition is in progress. But I'm probably misunderstanding the flow of events.

**Comment by jakearchibald** [comment]
The issue is if you quickly tick one item after another (imagine you'd completed the top 5 items in the TODO list). It feels like there's a decent chance a click will overlap with the transition.

**Comment by pfgithub** [comment]
Currently in chrome, interactivity seems to be completely blocked while a transition is running. This means they view transitions can only really be used for full-page transitions, so smaller transitions still need to be done the old way with both elements existing at once

**Comment by khushalsagar** [comment]
Interactivity is not blocked per se. Because hit testing works by sending the input event to what's drawing at the top , and the view transition pseudo-elements are always at the top of the DOM, they consume all the events. It's possible to prevent that.

If you want to do a transition which is in a DOM sub-tree, i.e. the rest of the DOM remains the same, you can try this CSS:

```css
/* A name is added to the root via UA css. Remove it so only the element which is changing transitions */
html {
  view-transition-name: none;
}

/* view-transition pseudo is sized to cover the complete viewport on top of the DOM. Setting pointer-events to none makes it so input events are sent to the DOM underneath */
html::view-transition {
  pointer-events: none;
}
```

That said, the current API is built with the assumption that its a full page transition. For example, the browser pauses rendering on the whole DOM during the transition. So while the above will work, you'd still see running animations (throughout the DOM) stop when the callback passed to startVT is running. We have a feature planned to allow running concurrent transitions in different sub-trees of the DOM : [scoped transitions](https://github.com/WICG/view-transitions/blob/main/explainer.md#transitions-targeted-to-a-specific-element).
