### ISSUE TITLE
High level options for customizing animation for offscreen elements

### ISSUE THREAD

**Issue by vmpstr** [WICG/view-transitions#84]
From the explainer:

Open question: Default animations work well for things which are at least partially in-viewport in both Page-A and Page-B, but it gets tricky if you consider a non-sticky header that scrolled out of view by 1000s of pixels.

**Comment by jakearchibald** [comment]
I don't have a good idea for this aside from another CSS property:

```css
.whatever {
  page-transition-clamp-position: just-out-of-viewport-please;
}
```

**Comment by jakearchibald** [comment]
This page documents the issue here https://static-misc-2.glitch.me/page-transition/#header-to-new-position-scrolled

**Comment by jakearchibald** [comment]
A high level solution here would be something like:

```css
.whatever {
  page-transition-offscreen-behavior: …;
}
```

Where the values could be:

- `default` - element takes its true position (the current behaviour).
- `clamp` - clamp the element's position so it's just out of view, compared to the other end of the animation.
- `absent` - behave as if the element is absent in this half of the transition.

But I'm going to look into lower-level solutions.
